### ISSUE TITLE
Commit-lərin yazılması

### ISSUE THREAD

**Issue by EldanizAkbar** [jalamirzayeva/PragmatechFoundationProject#3]
Zəhmət olmasa commit-ləri etdiyiniz dəyişiklərə uyğun yazın

**Comment by jalamirzayeva** [comment]
> Zəhmət olmasa commit-ləri etdiyiniz dəyişiklərə uyğun yazın

Git-də kiçik problem olduğuna görə kodları yazsam da github-a atmaq olmurdu.Bu gün həll etdim, bundan sonra commitlərin yazılmasına diqqət edəcəyəm.
